name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn run lint

      - name: Run Tests
        run: yarn run test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

  validate-container-build:
    name: Validate Container Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [build, lint-and-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build validation
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: "fastify-template:latest"
          load: true

      - name: Validate build size
        uses: wemake-services/docker-image-size-limit@2.2.0
        with:
          image: "fastify-template:latest"
          show_current_size: true
          size: "400MB"

  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Deploy
    needs: [build, validate-container-build]
    runs-on: ubuntu-latest
    environment:
      name: "production"
    permissions:
      contents: write
      id-token: write
      actions: write
    env:
      REPO: ${{ github.repository }}
      REPO_NAME: ${{ github.event.repository.name }}
      GH_TOKEN: ${{ secrets.ACTIONS_PAT }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      GCP_SA_EMAIL: ${{ secrets.SA_EMAIL }}
      GAE_SERVICE: fastify-template
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create app.yaml and .gcloudignore
        run: |
          echo "runtime: nodejs24"                   > app.yaml
          echo "instance_class: F1"                 >> app.yaml
          echo "service: ${{ env.GAE_SERVICE }}"    >> app.yaml
          echo "automatic_scaling:"                 >> app.yaml
          echo "  max_instances: 1"                 >> app.yaml
          echo "handlers:"                          >> app.yaml
          echo "  - url: /.*"                       >> app.yaml
          echo "    script: auto"                   >> app.yaml
          echo "    secure: always"                 >> app.yaml
          echo "env_variables:"                     >> app.yaml
          echo "  NODE_ENV: '${{ env.NODE_ENV }}'"  >> app.yaml

          echo ".git/"                               > .gcloudignore
          echo ".github/"                           >> .gcloudignore
          echo ".vscode/"                           >> .gcloudignore
          echo "node_modules/"                      >> .gcloudignore
          echo "src/"                               >> .gcloudignore
          echo ".env*"                              >> .gcloudignore
          echo ".gitignore"                         >> .gcloudignore
          echo ".prettierrc"                        >> .gcloudignore
          echo "Dockerfile"                         >> .gcloudignore
          echo "eslint.config.ts"                   >> .gcloudignore
          echo "jest.config.ts"                     >> .gcloudignore
          echo "LICENSE"                            >> .gcloudignore
          echo "nodemon.json"                       >> .gcloudignore
          echo "README.md"                          >> .gcloudignore
        shell: bash

      - id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.GCP_SA_EMAIL }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v3.0.1
        id: deploy_app
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
      - name: Update repository homepage (URL)
        run: |
          gh repo edit ${{ env.REPO }} --homepage "https://${{ env.GAE_SERVICE }}-dot-${{ env.GCP_PROJECT_ID }}.appspot.com"
