name: ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run Lint
        run: yarn run lint

      - name: Run Tests
        run: yarn run test

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn run build

  validate-container-build:
    name: Validate Container Build
    runs-on: ubuntu-latest
    needs: [build, lint-and-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build validation
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: "fastify-template:latest"
          load: true

      - name: Validate build size
        uses: wemake-services/docker-image-size-limit@2.2.0
        with:
          image: "fastify-template:latest"
          show_current_size: true
          size: "400MB"

  deploy:
    name: Deploy
    needs: [build, validate-container-build]
    runs-on: ubuntu-latest
    environment:
      name: "production"
    permissions:
      contents: write
      id-token: write
      actions: write
    env:
      REPO: ${{ github.repository }}
      REPO_NAME: ${{ github.event.repository.name }}
      GH_TOKEN: ${{ github.token }}
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}
      SA_EMAIL: ${{ secrets.SA_EMAIL }}
      SERVICE: fastify-template
      NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create app.yaml and .gcloudignore
        run: |
          echo "runtime: custom" > app.yaml
          echo "env: flexible" >> app.yaml
          echo "service: ${{ env.SERVICE }}" >> app.yaml
          echo "automatic_scaling:" >> app.yaml
          echo "  min_num_instances: 1" >> app.yaml
          echo "  max_num_instances: 1" >> app.yaml
          echo "instance_class: F1" >> app.yaml
          echo "handlers:" >> app.yaml
          echo "  - url: /.*" >> app.yaml
          echo "    script: auto" >> app.yaml
          echo "env_variables:" >> app.yaml
          echo "  NODE_ENV: '${{ env.NODE_ENV }}'" >> app.yaml
          echo ".git" > .gcloudignore
          echo ".github/" >> .gcloudignore
          echo "node_modules/" >> .gcloudignore
          echo "build/" >> .gcloudignore
          echo ".env*.local" >> .gcloudignore
          echo ".env.keys" >> .gcloudignore
        shell: bash

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to App Engine
        id: deploy_app
        run: |
          VERSION=v-$(git rev-parse --short HEAD)
          gcloud app deploy app.yaml \
            --quiet \
            --project=${{ env.GCP_PROJECT_ID }} \
            --version=$VERSION \
            --promote
          echo "DEPLOYMENT_URL=http://${{ env.SERVICE }}-${{ env.GCP_PROJECT_ID }}.appspot.com" >> $GITHUB_OUTPUT

      - name: Update repository homepage (URL)
        run: |
          gh repo edit ${{ env.REPO }} --homepage ${{ steps.deploy_app.outputs.DEPLOYMENT_URL }}
