name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create yarn cache
        uses: actions/cache@v4.3.0
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js LTS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: "lts/*"
          check-latest: true
          architecture: x64
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn run lint

      - name: Run tests
        run: yarn run test --coverage

      - name: Save coverage reports artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: coverage-${{github.run_id}}
          path: ./coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ env.CODECOV_TOKEN }}

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js LTS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          check-latest: true
          architecture: x64
          cache: yarn

      - name: Restore node_modules cache
        uses: actions/cache@v4.3.0
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: build-${{github.run_id}}
          path: |
            ./build
            ./public
            ./package.json
            ./yarn.lock

  validate-container:
    needs: [build]
    name: Validate Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: "${{ github.repository }}:latest"
          load: true

      - name: Validate image size
        uses: wemake-services/docker-image-size-limit@2.2.0
        with:
          image: "${{ github.repository }}:latest"
          show_current_size: true
          size: "400MB"

      - name: Save image to file
        run: docker save ${{ github.repository }}:latest -o ./image-${{ github.run_id }}.tar

      - name: Upload image artifacts
        uses: actions/upload-artifact@v5.0.0
        with:
          name: image-${{github.run_id}}
          path: ./image-${{ github.run_id }}.tar
